# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-05-29 12:16+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: zibanu/django/db/models/dated_model.py:23
msgid "Created at"
msgstr "Creado el"

#: zibanu/django/db/models/dated_model.py:24
msgid "Modified at"
msgstr "Modificado el"

#: zibanu/django/db/models/fields/phone_field.py:22
msgid "A Phone Field object"
msgstr "Campo tipo teléfono"

#: zibanu/django/db/models/fields/phone_field.py:45
msgid "'dial_code' and 'phone_number' keys are required."
msgstr "'codigo pais' y 'número telefónico' son claves requeridas."

#: zibanu/django/db/models/fields/phone_field.py:47
msgid "Number of keys major than required. Please try again."
msgstr ""
"El número de claves es mayor que las requeridas. Por favor inténtelo de "
"nuevo."

#: zibanu/django/db/models/fields/phone_field.py:49
msgid "Type of field keys are wrong. Please try again."
msgstr ""
"El tipo de claves de campo son erradas. Por favor inténtelo nuevamente."

#: zibanu/django/db/models/fields/phone_field.py:51
msgid "Country code is not valid. Please try again."
msgstr "El código de país no es válido. Por favor inténtelo nuevamente."

#: zibanu/django/db/models/manager.py:52
#, fuzzy
#| msgid "Object does not exists."
msgid "The object does not exists."
msgstr "El objeto no existe."

#: zibanu/django/lib/classes/code_generator.py:190
msgid "The generated values are invalid."
msgstr "El valor generado es inválido."

#: zibanu/django/lib/enums/dial_codes.py:20
msgid "Argentina"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:21
msgid "Bolivia"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:22
msgid "Brazil"
msgstr "Brasil"

#: zibanu/django/lib/enums/dial_codes.py:23
msgid "Chile"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:24
msgid "China"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:25
msgid "Colombia"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:26
msgid "Costa Rica"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:27
msgid "Cuba"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:28
#: zibanu/django/lib/enums/dial_codes.py:29
#: zibanu/django/lib/enums/dial_codes.py:30
msgid "Dominican Republic"
msgstr "República Dominicana"

#: zibanu/django/lib/enums/dial_codes.py:31
msgid "Ecuador"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:32
msgid "Egypt"
msgstr "Egipto"

#: zibanu/django/lib/enums/dial_codes.py:33
msgid "El Salvador"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:34
msgid "France"
msgstr "Francia"

#: zibanu/django/lib/enums/dial_codes.py:35
msgid "Guatemala"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:36
msgid "Guyana"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:37
msgid "Honduras"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:38
msgid "Italy"
msgstr "Italia"

#: zibanu/django/lib/enums/dial_codes.py:39
msgid "Kazakhstan/Russia"
msgstr "Rusia/Kasajistan"

#: zibanu/django/lib/enums/dial_codes.py:40
msgid "Mexico"
msgstr "Méjico"

#: zibanu/django/lib/enums/dial_codes.py:41
msgid "Nicaragua"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:42
msgid "Panama"
msgstr "Pánama"

#: zibanu/django/lib/enums/dial_codes.py:43
msgid "Paraguay"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:44
msgid "Peru"
msgstr "Perú"

#: zibanu/django/lib/enums/dial_codes.py:45
#: zibanu/django/lib/enums/dial_codes.py:46
msgid "Puerto Rico"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:47
msgid "Spain"
msgstr "España"

#: zibanu/django/lib/enums/dial_codes.py:48
msgid "United Kingdom"
msgstr "Reino Unido"

#: zibanu/django/lib/enums/dial_codes.py:49
msgid "United States/Canada"
msgstr "Estados Unidos/Canada"

#: zibanu/django/lib/enums/dial_codes.py:50
msgid "Uruguay"
msgstr ""

#: zibanu/django/lib/enums/dial_codes.py:51
msgid "Venezuela"
msgstr ""

#: zibanu/django/rest_framework/decorators.py:55
msgid "Permission name or tuple is required."
msgstr "Nombre del permiso o lista de permisos es requerida."

#: zibanu/django/rest_framework/decorators.py:64
#: zibanu/django/rest_framework/exceptions/api_exception.py:41
#: zibanu/django/rest_framework/exceptions/permission_denied.py:25
msgid "You do not have permission to perform this action."
msgstr "No posee permisos para ejecutar esta acción."

#: zibanu/django/rest_framework/exceptions/api_exception.py:33
msgid "API Exception"
msgstr "Excepción tipo API"

#: zibanu/django/rest_framework/exceptions/api_exception.py:38
msgid "Object has not been created."
msgstr "El objeto no ha sido creado."

#: zibanu/django/rest_framework/exceptions/api_exception.py:39
msgid "Generic error."
msgstr "Error genérico."

#: zibanu/django/rest_framework/exceptions/api_exception.py:40
msgid "You are not authorized for this resource."
msgstr "No está autorizado para utilizar este recurso."

#: zibanu/django/rest_framework/exceptions/api_exception.py:42
msgid "Object does not exists."
msgstr "El objeto no existe."

#: zibanu/django/rest_framework/exceptions/api_exception.py:43
msgid "Data validation error."
msgstr "Error en validación de datos."

#: zibanu/django/rest_framework/exceptions/api_exception.py:44
msgid "Data required not found."
msgstr "El dato requerido no existe."

#: zibanu/django/rest_framework/exceptions/api_exception.py:45
#, fuzzy
#| msgid "Not controlled exception error."
msgid "Not controlled exception error. Please contact administrator."
msgstr "Error de excepción no controlada."

#: zibanu/django/rest_framework/exceptions/not_implemented_exception.py:27
msgid "Service not implemented"
msgstr "Servicio no implementado"

#: zibanu/django/rest_framework/fields/hybrid_image.py:28
msgid "The width or height of the file is invalid."
msgstr "El ancho o alto del archivo es inválido."

#: zibanu/django/rest_framework/fields/hybrid_image.py:76
#, fuzzy
#| msgid "Error sending email."
msgid "Error encoding image file"
msgstr "Error enviando el correo."

#: zibanu/django/rest_framework/viewsets/model_viewset.py:71
msgid "Invalid Token"
msgstr "Token inválido"

#: zibanu/django/utils/error_messages.py:21
msgid "Error! The field is required."
msgstr "Error! El campo es requerido."

#: zibanu/django/utils/error_messages.py:22
msgid "Error! Record has not been created."
msgstr "Error! El registro no ha sido creado."

#: zibanu/django/utils/error_messages.py:23
msgid "Error! Record has not been updated."
msgstr "Error! El registro no ha sido actualizado."

#: zibanu/django/utils/error_messages.py:24
msgid "Error! There is not record matching."
msgstr "Error! No existen registros que coincidan."

#: zibanu/django/utils/error_messages.py:25
msgid "Error! Record can not be deleted."
msgstr "Error! El registro no ha sido eliminado."

#: zibanu/django/utils/error_messages.py:26
msgid "Error! The data required not found."
msgstr "Error! Los datos requeridos no se encuentran."

#: zibanu/django/utils/error_messages.py:27
msgid "Error at database."
msgstr "Error genérico en la base de datos."

#: zibanu/django/utils/error_messages.py:28
msgid "Data required at request not found."
msgstr "El dato requerido no existe."

#: zibanu/django/utils/error_messages.py:29
msgid "Error! Exception not controlled."
msgstr "Excepción no controlada"

#: zibanu/django/utils/generic_utils.py:49
msgid "Could not load import serializer class: "
msgstr "No se puede importar la clase serializadora: "

#: zibanu/django/utils/mail.py:59
#, python-format
msgid "Error sending mail: %(error_str)s with code: %(error_code)d."
msgstr "Error enviando el correo: %(error_str)s con el código: %(error_code)d."

#: zibanu/django/utils/mail.py:60
#, fuzzy, python-format
#| msgid "Syntax error loading template '{}'"
msgid "Syntax error loading template %(template)s."
msgstr "Error de sintaxis cargando la plantilla '{}'"

#: zibanu/django/utils/mail.py:61
#, fuzzy, python-format
#| msgid "Template '{}' does not exist."
msgid "Template %(template)s does not exists."
msgstr "La plantilla %(template)s no existe."

#~ msgid "OASIS Error. The object does not exists."
#~ msgstr "El objeto no existe."

#~ msgid "Data request not found."
#~ msgstr "El dato requerido no existe."
